[project]
name = "meals-ua-uv"
version = "0.1.0"
description = "UV fork of meals@ua"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "certifi==2018.11.29",
    "chardet==3.0.4",
    "idna==2.8",
    "requests==2.21.0",
    "urllib3>=1.24.2",
]
